version: '2'
services:

  irls_server:
    build: .
    container_name: irls_server
    ports:
     - "9090:3001"
    volumes_from:
      - irls_data:ro
    depends_on:
     - irls_data
    # environment:
    #   NODE_ENV: dev


  irls_data:
    build: ./data/
    # dockerfile: Dockerfile_content
    container_name: irls_data

  irls_agent:
    build: ./server/agent/
    container_name: irls_agent