define([

   './submachine/module',
   './localstorage/module',
   './longrunning/module',
   './phonegap/module',
   './userinputblockerregistry/module',
   './anchorscroll/module',
   './applicationframe/module',
   './bodyclass/module',
   './catchkey/module',
   './click/module',
   './compile/module',
   './componentfactory/module',
   './exception/module',
   './fastclickconfig/module',
   './featuredetector/module',
   './focus/module',
   './hotkey/module',
   './input/module',
   './inputcombo/module',
   './inputselect/module',
   './layout/module',
   './localize/module',
   './longrunning/module',
//   './oncontextmenu/module',
   './onload/module',
   './onelementresize/module',
   './http/module',
   './mediadetector/module',
   './popup/module',
   './render/module',
   './selection/module',
   './swipe/module',
   './tabs/module',
   './texttransform/module',
   './validation/module',
   './settings/module',
   './appurl/module',
   './i18n/module',
   './message/module',
   './tracing/module',
   './util/module',
   './font/module',
   './scrolling/module',
   './sticky/module',
   './conditionalattr/module'

], function(){});

